server:
  port: 8888

# registry to Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        # store all config properties or yaml file into this git url
        git:
          uri: https://github.com/kimhab11/employee-config-server.git
  application:
    name: config-server

# Actuators
management:
  security:
    # disabled security
    enabled: false
  endpoints:
    web:
      exposure:
        # expose all routs
        include: "*"



